# Generated by Django 4.2.4 on 2024-12-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='商品名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('category', models.CharField(choices=[('食材', '食材'), ('調味料', '調味料'), ('その他', 'その他')], max_length=50, verbose_name='カテゴリ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='単価')),
                ('supplier', models.CharField(max_length=255, verbose_name='仕入れ先')),
                ('quantity', models.FloatField(verbose_name='在庫量')),
                ('unit', models.CharField(default='kg', max_length=50, verbose_name='単位')),
                ('reorder_level', models.FloatField(default=0, verbose_name='発注必要量')),
                ('warning_flag', models.BooleanField(default=False, verbose_name='発注警告')),
            ],
        ),
    ]
