# Generated by Django 4.2.4 on 2024-12-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='reorder_level',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='warning_flag',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='code',
            field=models.CharField(default='default_code', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='current_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='min_stock',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='supplier',
            field=models.CharField(max_length=200),
        ),
    ]
