# Generated by Django 4.2.4 on 2024-12-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('date', models.DateField(verbose_name='勤務日')),
                ('start_time', models.TimeField(verbose_name='出勤時間')),
                ('end_time', models.TimeField(verbose_name='退勤時間')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備考')),
            ],
        ),
    ]
